### ISSUE TITLE
[2] Implementar layout de visualização dos horários da academia

### ISSUE THREAD

**Issue by thomastbb** [gmachamilton/Aquidemia-Projeto-IF977#13]
Implementar layout de visualização dos horários da academia relacionados à #10 
Ele deve ser simples e direto: mostrar os horários e um botão para voltar à página anterior

**Comment by ardmn9** [comment]
Adicionado no commit 7a5ca604509001603f8d0a963c0bbe1c63d5a1d4

**Comment by thomastbb** [comment]
Entre
