### ISSUE TITLE
Feedback Cadastrar histórias no gitHub

### ISSUE THREAD

**Issue by lsca** [gmachamilton/Aquidemia-Projeto-IF977#14]
Fala galera, tudo certinho??

Então, vocês estão criando issues para vários participantes. A ideia de uma issue é que ela seja direcionada a um unico participante. Caso não dê para fazer isso, vocês deveriam reduzir o esforço necessário para o cumprimento dessa issue e dividi-la em mais issues. Se é para desenvolver a HU 10, então é necessário destrinchar a HU 10 em mínimos esforços por participantes(issues), e atribui-los as issues.

Nota final: **8**

Qualquer duvida só responder essa issue, caso contrario, só fecha-la.

Att,

**Comment by thomastbb** [comment]
Não entendi, não tem nenhuma issue para mais de um participante, somente as issues de histórias de usuário, porém essas issues somente mostram os esforços dos participantes das issues (tasks) menores que JUNTAS são necessárias para a implementação dessas HUs. Do jeito que criei, elas não dividem os papéis nem são as tasks propriamente, as tasks já estão divididas entrem os participantes e somente um participante por task. A exemplo da HU 2, ela só serve como uma visualização das duas tasks necessárias para implementar a HU, no comentário dela que está escrito é mencionado as duas tasks que juntas fechariam a HU 2 e não definindo que os dois assignees da HU farão a mesma coisa nela. Isso pelo menos na iteração 2.

**Comment by thomastbb** [comment]
É por isso que falei "pelo menos na iteração 2". Pensava que essa correção feita agora era apanas para a iteração 2, já que a iteração 1 já ta praticamente morta e enterrada, esses exemplos que você citou são da nossa primeira iteração (por isso o [1]) antes de dar uma organizada nas issues e do professor explicar a gente em sala como fazer durante a apresentação da iteração 1 (posterior ao postmortem). Preciso consertar as issues da iteração 1 também? Isso ia desorganizar as issues por data mas ok se for necessário.
