### ISSUE TITLE
Feedback Cadastrar histórias no gitHub

### ISSUE THREAD

**Issue by lsca** [gmachamilton/Aquidemia-Projeto-IF977#35]
Feedback Cadastrar histórias no gitHub

Fala pessoa, tudo certinho??

Show de bola galera, chega deu orgulho de ver o milestone de vocês.

Nota final 10.

Qualquer duvida só responder a issue, caso contrario, só fechar ela.

**Comment by thomastbb** [comment]
Obrigado.
