### ISSUE TITLE
Feedback Postmortem - Iteração 3

### ISSUE THREAD

**Issue by mateusc42** [gmachamilton/Aquidemia-Projeto-IF977#41]
Iae pessoal, vou passar o feedback do postmortem da iteração 3 de vocês. :)

## Postmortem:
<ul>
  <li>Período -> OK</li>
  <li>O que estava planejado -> OK</li>
  <li>O que foi feito -> OK</li>
  <li>O que não foi feito -> OK</li>
  <li>O que está planejado pra próxima iteração -> OK</li>
  <li>Lições aprendidas -> OK</li>
  <li>Formato Markdown -> OK</li>
</ul>

### Nota Final: 10
---------------------------------------------------------------
> **Nota:** Adicionem a Label de FeedBack, não posso fazer isso porque não estou no projeto. Obrigado.

**Comment by thomastbb** [comment]
Obrigado.
