### ISSUE TITLE
Correção Iteração 3 - TDD, BDD e Modelo ER

### ISSUE THREAD

**Issue by ps1312** [gmachamilton/Aquidemia-Projeto-IF977#42]
## Testes BDD:

* Não possui nenhum caminho triste -> Possuem, porém, a cobertura de testes de caminhos tristes está muito pequena (só possui um caminho triste (usuário precisa de login). -2
* Todos os testes verdes -> Todos os testes passaram.

## Testes TDD:

* Não possui nenhum caminho triste -> Possuem caminhos tristes e felizes.
* Todos os testes verdes -> Todos os testes passaram.

#### Nota TDD: 5
---
## nota final: 8

---

## Modelo ER:

* Pessoal, a ideia é que o modelo de vocês seja a aplicação da teoria aprendida em banco de dados, ou seja, o modelo entidade relacional precisa ser respeitado, bem como suas entidades, relacionamentos e etc. Segue um exemplo do modelo ER esperado:

![image](https://user-images.githubusercontent.com/19872825/40931724-7a9d170e-6802-11e8-8ac6-0bfcadd1bfde.png)

## ~~nota final: 0~~

**Comment by thomastbb** [comment]
Obrigado!
