### ISSUE TITLE
Feedback iteração 0

### ISSUE THREAD

**Issue by SandrineMartins** [gmachamilton/Aquidemia-Projeto-IF977#9]
## Preenchimento do GitHub

Nome do projeto: **OK**
Descrição do Produto: **OK**
Justificativa do Projeto: **OK**
Especificação do papel de cada membro: **OK**

**Comment by SandrineMartins** [comment]
## Postmortem 


O que estava planejado: **OK**
O que foi feito: **OK**
O que não foi feito: **OK**
O que está planejado pra próxima iteração: **OK**
Lições aprendidas: **OK**
Formato Markdown: **OK**

### Nota final: 10

**Comment by SandrineMartins** [comment]
## Ata de reunião

Participantes da reunião: **OK**
Tópicos discutidos: **OK**
O que foi definido: **OK**
Formato Markdown: **OK**

### Nota final: 10

**Comment by SandrineMartins** [comment]
## Mockups e storyboards

Sequência: **OK**
Imagem bem ilustrada: **OK**

### Nota final: 10

> OBS: na página inicial há dois botões que levam para o mesmo lugar. Por quê?

**Comment by thomastbb** [comment]
Obrigado!
